import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
});

const stretch = localFont({
  src: "../assets/fonts/Stretch.otf",
  variable: "--stretch",
  weight: "400",
});

const highrise_bold = localFont({
  src: "../assets/fonts/Highrise_Bold.otf",
  variable: "--highrise_bold",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="es" className="bg-neutral-900 text-white">
      <body className={`${montserrat.className} ${stretch.variable} ${highrise_bold.variable} antialiased w-full min-h-svh flex flex-col items-center`}>
        {children}
      </body>
    </html>
  );
}